#!/usr/bin/env bash
# Check existence and type of school file

if [ ! -e school ]; then
  echo "school doesn’t exist"
else
  echo "school file exists"
  if [ -f school ]; then
    if [ -s school ]; then
      echo "school file is not empty"
    else
      echo "school file is empty"
    fi
  else
    echo "school is a directory"
  fi
fi
