#!/usr/bin/env bash
# Check existence, type, and emptiness of "school" file

if [ -e school ]; then
  if [ -f school ]; then
    echo "school is a regular file"
  elif [ -d school ]; then
    echo "school is a directory"
  fi
  if [ -s school ]; then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi
else
  echo "school file does not exist"
fi
